# Generated by Django 4.1.7 on 2023-02-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='alunos',
        ),
    ]
