# Generated by Django 4.1.7 on 2023-02-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0002_remove_cadeira_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='alunos',
            field=models.ManyToManyField(related_name='cadeiras_escritas', to='DRF.aluno'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadeiras_cadastradas', to='DRF.professor'),
        ),
    ]
